### ISSUE TITLE
能把NPC背走的BUG

### ISSUE THREAD

**Issue by liutingfenga** [SanCraftDev/Stacker#24]
这个插件能背走npc  能导致了服务器出现了很大的问题

**Comment by DavidCraftDev** [comment]
你对NPC使用的是哪个插件？
那你说的服务器大问题是什么意思？
(此信息来自翻译，因为我不懂中文)

**Comment by liutingfenga** [comment]
Citizens2

**Comment by DavidCraftDev** [comment]
你是否使用最新版本的Stacker插件？因为这个错误在我的测试服务器上没有发生。

**Comment by 2020Sanoj** [comment]
@liutingfenga can we close this issue?

**Comment by DavidCraftDev** [comment]
Hello?

**Comment by 2020Sanoj** [comment]
Closed because of inactivity and if we understand the bug report correctly, bug should be fixed
