### ISSUE TITLE
BUG: while having player on top of each other, if player who is being ridden press RIGHT-CLICK, the rider will become visually bugged for ridden player in the air

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [SanCraftDev/Stacker#91]
In this image you can see that i pressed RIGHT-CLICK as a player who is being ridden, so the player visually is not on his place anymore even though you can see rider's nametag above player who is being ridden still:
![image](https://github.com/user-attachments/assets/df1413ca-ff1b-4a6d-984d-00a3565a9b9c)

and when i as player who is being ridden press SHIFT to dismount whoever is ridding me, it pops into his normal state:
![image](https://github.com/user-attachments/assets/a1b93d25-d576-46aa-ad59-c2db28316911)

**Comment by Zoey2936** [comment]
does this also happen with an vanilla client?

**Comment by Zoey2936** [comment]
@DavidCraftDev

**Comment by MotikaCraft-TheJoshua** [comment]
> does this also happen with an vanilla client?

i only tested with vanilla client

**Comment by MotikaCraft-TheJoshua** [comment]
And please when you fix this bug, compile with Java17, not java21... @Zoey2936 @DavidCraftDev

**Comment by Zoey2936** [comment]
can you try with a real non npc player? also we reverted to java 17 a few months ago

**Comment by MotikaCraft-TheJoshua** [comment]
> can you try with a real non npc player? also we reverted to java 17 a few months ago

This was not npc player, this was real account, i joined with my alt "Test" account
ok great for java version!

**Comment by MotikaCraft-TheJoshua** [comment]
also please add citizens support

**Comment by MotikaCraft-TheJoshua** [comment]
any soon?

**Comment by Zoey2936** [comment]
this can't be reproduced
